language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- yarn install
before_script: 
script:
- yarn build
after_script:
- cd ./dist
- ls
- git init
- git config user.name "${USERNAME}"
- git config user.email "${EMAIL}"
- git add -A
- git commit -m "deploy"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: m802A8cPSIbteH0MxkPj4ogB8DukKBCrfFgljIqcFgzl7BTrxXeCkZDr4EBWue0JXejz2mtfjEmkk29xpjJdJXzb4gCvFvSeFIeKAZm3gYG3nMHOgK9Vqp4LHssKaJxwYEUne5IJq6tNWPf5ITFIIipN7O5eXsajHMmEWSiAjZ34GCQ03WZFG/jo53hOMSRvpteVQGNZMEw3TK8ELBc9vPrFEqXCXcWCXBfJ45RzGcfw32jxrsUXpNGEXr3nJgUrOOo9FwaomVcHSmD60kvhEQ1Neu1dJXvGwusGNpKlM5pdQ+vt8ep1nPe/XGgLGfQCxLIi8pcYGsEW8ejGANI9ORaykyTQXrsOazzxVta9Tex2+JcreDtTp5yvjR3aMzA0NEBFaSeFKqRmUicLqKiGMbuzArCQy0AvNahiONNkptZjhin0/YzzjHEceuCKOk+NByTZouFbHfzNx+eSrP2WoKcJFZlDR1cGNfq/goKbvRphelKcDc1u/kre88ksBbz8X4fuCmJsKPgJaDvB9p5Cpz3yuJ+0a9CzAYKtMzB/Az9WA+cgYR1+5s3A6hjSlsBnqyLCfVyo5j3F5h15jCRDVST3QIvBeeX7blWLhzWR0slHAn819cgTKXeELn6uT2YBmDdGCo8OKgCAce6MyQLLlYcvkgMRJdwvkJEPPEFV5RU=
    on_success: always
    on_failure: always
    template:
    - Repo `%{repository_slug}`build (<%{build_url}|#%{build_number}>) for commit
      (<%{compare_url}|%{commit}>) on branch `%{branch}` by `%{author}`.
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
env:
  global:
  - USERNAME: snowball1990
  - EMAIL: snowballer0705@gmail.com
  - GH_REF: github.com/Damo-web/docs.git
  - BRANCHNAME: gh-pages
