language: node_js
node_js: stable

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - yarn install

before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - yarn build

after_script:
  - cd ./dist
  - ls
  - git init
  - git config user.name "${USERNAME}"
  - git config user.email "${EMAIL}"
  - git add -A
  - git commit -m "deploy"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master

notifications:
  slack:
    rooms:
      - secure: 5i94uZe/YGaqUKwVO/1wtBQfJXs5PnDOlcxrw9dwCfZnRYhyK0XGhjNtc40qwG4ULIjeD8kbKGeCF8hz2kjcr/l4ce1zVuJcz9SRT3E61xvpf34eeGl/mUuf7Hz2tyLQ0y+5G9TCrcSkOv+7T/GBacTLmQOPCKOJbMUF7etCrb2m5EHbYON3xrNf8JXf7BqJYYTD31O+d/eCXEp7JVLtQVU8o5u7Y4rjRxKKiDcT5w3ISIcXq2g991KEe/2GXf6ZP77CVoATz/oC5c+xbWlZB02Wm6WtSxU2PyC2nxCmPxyURsNXnvgwOYeL5ZHoUB0rvtwYLtyzlAEPGC2oTsfLH5H8GUxaUrMZ585f/Bgf+rA2vDA9uRVri/IsoeoFWTYyP8OUizlcz1YIEgJBgm4V2MzftHlRg9NHZddRLfnpgLHMPFoSEypqiyJyxU0HXJYlrZ+nS7Vej3OrRSlOdW/tTL5F16d332INF+Z5peTuNhD2Jd1evgFzezhMHMktahl9Ij+rHZwwSaHV3Sf9kQVRTxrir/nSK9GmsLkadEEiFQFr2P/gwFVjWsF4xzR150371nxLTGBj/aqAackEof4auCOOVF5AUoXqmbBha0XuvMTPCzP9jxuIVxnXXp0jQovYG9vWZgkoi9JQuMEF5pO/ZsBmDrITG3jUccvwdEfPbDc=
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"

env:
 global:
   - USERNAME: snowball1990
   - EMAIL: snowballer0705@gmail.com
   - GH_REF: github.com/Damo-web/docs.git
   - BRANCHNAME: gh-pages