language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- yarn install
before_script: 
script:
- yarn build
after_script:
- cd ./dist
- ls
- git init
- git config user.name "${USERNAME}"
- git config user.email "${EMAIL}"
- git add -A
- git commit -m "deploy"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
notifications:
  slack:
    secure: 4wfgYuOLuvuraPQwh3N5yZdaGxcIF99qXp5WrRmFs/yAZgMBIj/h+yXfFruD0GkWkGnuoppnWMWpPSNAqP3Ncr1/uswolCBilgr2afX/gYjqOsT8WNkBqL1Z/ltMqaQ6v90XXnUXYesqcK0RYL4Vm4s2lvMONVW/TmpOscZzZC8OKIcnAKFK3NhqlaybUV3XGzekHT74zztEMjRjqQHyd0F7JASlzma4LjSYHXSTEg1TOpVLMmvsRsI8nsgN9itOQefL8ovx0hVqbnEMnrsHOrFlS8F6tUwHer8/bvBSBS5A+UGYovg5GeQ1Me1h2ghZumOnSiE8yUt2tysJpqXoihbi5wykLXbDZyz3T5vqg4bDl4Ip6n2AWonIRjHtYEfyYJ8WYhZgngZ+EIyLhh21xhd+IzktLGtmszNBS6TbrI17FKwOBkctBoYIX5zyJ1PfTDdqo6sDAab5V+wpPdPm7F4yFbIADCP/hwFx+a5x9s3nobJRgPNCk+n/MND3cVKeNx/RxnQNu/GaUObp0wiapCPgbpH1pGO4ZHI8/9OpwAxH84qk7uyuBDzvDviw8Yf7NI7dAIKbwJyS6X0jfJApacomupKtnlORJJV/6kL7yzespP35rln1ktZ+sUL6lersw04gvw6QfHDpOBUuEBiApVs71XFmfKlR6R+/7hxsBoA=
env:
  global:
  - USERNAME: snowball1990
  - EMAIL: snowballer0705@gmail.com
  - GH_REF: github.com/Damo-web/docs.git
  - BRANCHNAME: gh-pages
