language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- yarn install
before_script: 
script:
- yarn build
after_script:
- cd ./dist
- ls
- git init
- git config user.name "${USERNAME}"
- git config user.email "${EMAIL}"
- git add -A
- git commit -m "deploy"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      secure: aw21xF1xbPLyo0D/SMvp2IzlUiWTYTArdH4gLPKx+Uk2ddOjxBIv4ZsEJw56FMHm00w3BxGvV7ZViS06XVULIlV39y1ptfnC4bVgwXDmLtspgXudnPJI8y98NqJxnJCVbkYue5PU1xOc/4nirWMUHgrs1TPPnHVXsb+2wiBB1VEpYPdO78IqHxfuPL7qwC8RyuEfsyua4/kpeI21SXwp3ObokWtREbd9PRWFLvGNptPZzSTQ61sPuFkt9zBkqEjgz3QkgOWfc3FMdxk37ybDgX8a6OBXQBwjGuWoNYWl/VVCqDLMunxmqjkQ6G56SM+rTd0+a8SNR6MoIqa03eCHAm2ClBCYsQLnnVlO2FqcL5vkHex+DVEhGu9LmUEmOYIJXwEhYoAJ+Ih7xsI07vJwpLgZlx4M8fDeQYrQPirvUZs6hlx58B5RZtlZiu9a5+WqSx1LYD0JEmnGJ7XQzt2qxWhoiDhD6iluHi/arkVr7XuYcfYVxQgGkcxEPY7yveQ1RES+c//V3cHV86gq9jThkxFAdX1+hVD0nJOZRgt9DFTGdUVPvcq3lhNdlCq7F+0tI6fo5f+lNZ014b1qxvBqmIPgFj1ptno/WKYfpXjy75GWoLF4dg2Ls4K5EvVgkRKsWLgDW75woJ8+OuaBREbeJRQehI1ZzwLLUxdjZs/tpq4=
    on_success: always
    on_failure: always
    template:
    - Repo `%{repository_slug}`build (<%{build_url}|#%{build_number}>) for commit
      (<%{compare_url}|%{commit}>) on branch `%{branch}` by `%{author}`.
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
env:
  global:
  - USERNAME: snowball1990
  - EMAIL: snowballer0705@gmail.com
  - GH_REF: github.com/Damo-web/docs.git
  - BRANCHNAME: gh-pages
