language: node_js
node_js: stable
cache:
  directories:
  - node_modules
install:
- yarn install
before_script: 
script:
- yarn build
after_script:
- cd ./dist
- ls
- git init
- git config user.name "${USERNAME}"
- git config user.email "${EMAIL}"
- git add -A
- git commit -m "deploy"
- git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
branches:
  only:
  - master
notifications:
  slack:
    rooms:
      - totorocorp:k4RhBu6TpTLBdQ1hPTKMSglB#web-notification
    on_success: always
    on_failure: always
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{message}"
env:
  global:
  - USERNAME: snowball1990
  - EMAIL: snowballer0705@gmail.com
  - GH_REF: github.com/Damo-web/docs.git
  - BRANCHNAME: gh-pages
